Repository WaggleWaggle-v2/waggle-frontend, pull requests merged in 2024-08, with the labels that each got.

#4 로그인 페이지 레이아웃 (반응형) 완성
  src/App.tsx
  src/Router.tsx
  src/assets/.gitkeep
  src/assets/icons/social-login/symbol-google.svg
  src/assets/icons/social-login/symbol-kakao.svg
  src/assets/icons/social-login/symbol-naver.svg
  src/assets/images/title.png
  src/assets/images/typography.png
  src/fonts/EBSHMJESaeron-L.woff
  src/fonts/EBSHMJESaeron-R.woff
  src/fonts/EBSHMJESaeron-SB.woff
  src/fonts/EBSHunminjeongeum-L.woff
  src/fonts/EBSHunminjeongeum-R.woff
  src/fonts/EBSHunminjeongeum-SB.woff
  src/pages/Login/components/SocialLoginButtonList.tsx
  src/pages/Login/constants/socialLoginInfo.ts
  src/pages/Login/index.tsx
  src/pages/index.ts
  src/styles/fonts.js
  src/styles/myReset.js
  tsconfig.app.json
Labels: Page, UI

#7 design: color pallette 추가 및 로그인 페이지 적용
  src/pages/Login/components/SocialLoginButtonList.tsx
  src/pages/Login/index.tsx
  src/styles/colors.js
  src/styles/myReset.js
Labels: UI

#10 Feature/nickname section
  src/Router.tsx
  src/assets/icons/door-close.svg
  src/assets/icons/door-open.svg
  src/components/.gitkeep
  src/components/PrimaryButton/index.tsx
  src/components/PrimaryInput/index.tsx
  src/components/PrimaryInput/utils/adjustTextareaHeight.ts
  src/components/template/SettingTemplate.tsx
  src/pages/Login/components/SocialLoginButtonList.tsx
  src/pages/home/Root.tsx
  src/pages/index.ts
  src/pages/setup/components/SetNickname.tsx
  src/pages/setup/components/SetPublicity.tsx
  src/pages/setup/constants/publicitySelect.ts
  src/pages/setup/index.tsx
  src/pages/setup/types/type.ts
  src/pages/setup/utils/isCompleteKoreanWord.ts
  src/styles/myReset.js
Labels: COMPONENT, Page, UI

#13 초기 닉네임/공개여부 설정 페이지 반응형 적용(mobile)
  src/components/PrimaryButton/index.tsx
  src/components/PrimaryInput/index.tsx
  src/components/template/SettingTemplate.tsx
  src/pages/setup/components/SetNickname.tsx
  src/pages/setup/components/SetPublicity.tsx
  src/pages/setup/index.tsx
  src/styles/myReset.js
Labels: COMPONENT, UI, Responsive

#14 NavBar UI 작업
  src/assets/icons/cross-line.svg
  src/assets/icons/kebab.svg
  src/assets/icons/right-arrow.svg
  src/assets/images/nav-bottom.svg
  src/assets/images/symbol-logo.png
  src/components/header/index.tsx
  src/components/header/nav/index.tsx
  src/pages/Root.tsx
Labels: UI

#15 추가 꾸미기 단계별 ui 설계 및 반응형 적용
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/icons/modal-close.svg
  src/assets/images/profiles/WGWG-profile-Image-01.jpg
  src/assets/images/profiles/WGWG-profile-Image-02.jpg
  src/assets/images/profiles/WGWG-profile-Image-03.jpg
  src/assets/images/profiles/WGWG-profile-Image-04.jpg
  src/assets/images/profiles/WGWG-profile-Image-05.jpg
  src/assets/images/profiles/WGWG-profile-Image-06.jpg
  src/assets/images/profiles/WGWG-profile-Image-07.jpg
  src/assets/images/profiles/WGWG-profile-Image-08.jpg
  src/assets/images/profiles/WGWG-profile-Image-09.jpg
  src/assets/images/publicity/open.png
  src/assets/images/publicity/private.png
  src/assets/images/test-main.jpg
  src/assets/images/theme/dark.png
  src/assets/images/theme/light.png
  src/components/PrimaryButton/index.tsx
  src/components/PrimaryInput/index.tsx
  src/components/PrimaryTextarea/index.tsx
  src/components/PrimaryTextarea/utils/adjustTextareaHeight.ts
  src/components/template/ModalTemplate.tsx
  src/components/template/SettingTemplate.tsx
  src/constants/MaxLength.ts
  src/pages/Login/index.tsx
  src/pages/index.ts
  src/pages/main/components/AdditionalSetup.tsx
  src/pages/main/components/AdditionalSetupModal.tsx
  src/pages/main/components/InitAdditionalSetupModal.tsx
  src/pages/main/components/SetIntro.tsx
  src/pages/main/components/SetProfile.tsx
  src/pages/main/components/SetTheme.tsx
  src/pages/main/constants/profile-images.ts
  src/pages/main/constants/theme.ts
  src/pages/main/index.tsx
  src/pages/setup/components/SetPublicity.tsx
  src/pages/setup/constants/publicitySelect.ts
  src/pages/setup/index.tsx
  src/pages/setup/utils/isCompleteKoreanWord.ts
  src/styles/myReset.js
Labels: COMPONENT, UI, Responsive

#18 Setup페이지 반응형 헤더 적용 및 ProgressBar 구현
  src/assets/icons/left-arrow.svg
  src/components/PrimaryTextarea/index.tsx
  src/components/header/index.tsx
  src/components/header/nav/index.tsx
  src/components/template/ProgressBar.tsx
  src/components/template/SettingTemplate.tsx
  src/constants/.gitkeep
  src/constants/maxLength.ts
  src/constants/setupTotalStep.ts
  src/pages/Root.tsx
  src/pages/main/components/AdditionalSetupModal.tsx
  src/pages/main/components/SetIntro.tsx
  src/pages/setup/index.tsx
  src/styles/headerHeight.js
Labels: COMPONENT, UI

#19 Setup page refactor
  src/components/header/index.tsx
  src/components/template/ModalTemplate.tsx
  src/components/template/ProgressBar.tsx
  src/pages/Login/index.tsx
  src/pages/Root.tsx
  src/pages/main/components/AdditionalSetup.tsx
  src/pages/main/components/AdditionalSetupModal.tsx
  src/pages/main/index.tsx
  src/pages/setup/index.tsx
  src/styles/zIndex.js
Labels: FIX, Refactor
